import { StyleSheet } from "react-native";
import { Colors } from "../../constants/Colors";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.surfaceLowest },
  kav: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colors.surfaceHigh,
    backgroundColor: "#f5f6f7eb",
    gap: 10,
  },
  backBtn: { padding: 4 },
  headerInfo: { flex: 1, minWidth: 0 },
  headerName: { fontSize: 16, fontWeight: "500", color: Colors.onSurface },
  headerHandle: { fontSize: 14, fontWeight: "500", color: Colors.primary },
  headerSub: { fontSize: 13, color: Colors.onSurfaceVariant, marginTop: 1 },
  headerActions: { flexDirection: "row", gap: 2 },
  headerBtn: { padding: 8, borderRadius: 10 },
  messageList: { paddingHorizontal: 12, paddingVertical: 12 },
  typingRow: { paddingHorizontal: 16, paddingVertical: 4 },
  typingText: { fontSize: 11, color: Colors.primary, fontStyle: "italic" },
  inputBar: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: Colors.surfaceHigh,
    backgroundColor: "#f5f6f7eb",
  },
  mediaPreview: {
    marginBottom: 8,
    alignSelf: "flex-start",
    position: "relative",
  },
  mediaThumb: {
    width: 90,
    height: 90,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: Colors.primary,
  },
  mediaRemove: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: Colors.error,
    borderRadius: 12,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 28,
    backgroundColor: Colors.surfaceLow,
  },
  attachBtn: { padding: 4, paddingBottom: 6, opacity: 0.5, marginBottom: -2 },
  textInput: {
    flex: 1,
    fontSize: 14,
    color: Colors.onSurface,
    maxHeight: 120,
    paddingVertical: 6,
  },
  sendBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
  },
  sendBtnDisabled: { opacity: 0.4 },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  emptyText: { fontSize: 15, color: Colors.onSurfaceVariant },
  requestBanner: {
    padding: 18,
    borderTopWidth: 1,
    borderTopColor: Colors.surfaceHigh,
    backgroundColor: "#ffffff",
    alignItems: "center",
    gap: 14,
  },
  requestText: {
    fontSize: 14,
    color: Colors.onSurface,
    textAlign: "center",
    lineHeight: 20,
    fontWeight: "500",
  },
  requestActions: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  acceptButton: {
    flex: 1,
    backgroundColor: Colors.primary,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  acceptText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
  },
  declineButton: {
    flex: 1,
    backgroundColor: Colors.surfaceHigh,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  declineText: {
    color: Colors.error,
    fontWeight: "700",
    fontSize: 14,
  },
  waitingBanner: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderTopWidth: 1,
    borderTopColor: Colors.surfaceHigh,
    backgroundColor: Colors.surfaceLowest,
    alignItems: "center",
    justifyContent: "center",
  },
  waitingText: {
    fontSize: 13,
    color: Colors.outline,
    textAlign: "center",
    lineHeight: 18,
    fontStyle: "italic",
  },
});
